version: '3.4'

services:
  db:
    image: 'mysql:5.7'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=livredor
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - .data:/var/lib/mysql
    networks:
      - merch
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
networks:
  merch:
    driver: bridge